### ISSUE TITLE
[Suggestion] : Adding Bottom Navigation Bar

### ISSUE THREAD

**Issue by ayato91** [danger-ahead/flutter_dictionary#10]
It would be great if there is a Bottom Navigation Bar instead of Tab Bar in the app screens.

**Comment by danger-ahead** [comment]
> It would be great if there is a Bottom Navigation Bar instead of Tab Bar in the app screens.

Can do. Go ahead!

**Comment by ayato91** [comment]
@danger-ahead 
Merge this changes and later we can upgrade readme.md file

**Comment by danger-ahead** [comment]
@ayato91 can you fix the README as well? need to clean up the `images` dir as well
