### ISSUE TITLE
Add dark mode screenshots

### ISSUE THREAD

**Issue by HarshMakwana27** [danger-ahead/flutter_dictionary#19]

**Comment by HarshMakwana27** [comment]
Okay, assign the issue.

**Comment by RileeyL** [comment]
Hello! @danger-ahead is this still open, and if so, what document would you like dark mode screenshots added to

**Comment by HarshMakwana27** [comment]
@RileeyL , @danger-ahead I can do this only after #25 is solved

**Comment by danger-ahead** [comment]
> @RileeyL , @danger-ahead I can do this only after #25 is solved 

Solved
