### ISSUE TITLE
[BUG] Multiple toast messages are appearing

### ISSUE THREAD

**Issue by nandhagobal** [danger-ahead/flutter_dictionary#23]
Hi @danger-ahead, After changing the theme of the app many times suddenly, the toast messages are coming one by one in the order of how we changed the theme. Example if we change theme in this order dark->system default->light , toast messages is like dark toast message(lay say 2 sec displaying)->system default(2sec)->Light message(2 sec). Expected should be dismiss the existing toast when new toast is added.

**Comment by danger-ahead** [comment]
Sure. Have assigned you.
