### ISSUE TITLE
[BUG] Dark mode is not working properly in result screen

### ISSUE THREAD

**Issue by nandhagobal** [danger-ahead/flutter_dictionary#25]
hi @danger-ahead in dark mode, the result screen fonts are not visible and the pronunciation ui also not visible properly.

<img width="251" alt="Screenshot 2023-10-08 at 9 34 57 AM" src="https://github.com/danger-ahead/flutter_dictionary/assets/59615972/a39cdbc2-f6d8-45bf-b542-1215c87f61ce">

**Comment by danger-ahead** [comment]
Assigned!

**Comment by HarshMakwana27** [comment]
hi @nandhagobal, and the scaffoldmessenger's font is also not visible properly in dark mode

**Comment by nandhagobal** [comment]
hi @HarshMakwana27 after fix it is looking like this. It is ok right.
<img width="302" alt="Screenshot 2023-10-09 at 10 42 31 AM" src="https://github.com/danger-ahead/flutter_dictionary/assets/59615972/9f9896af-895e-41b4-8a32-2eddbed86b2b">
