### ISSUE TITLE
pronunciation button covering the text

### ISSUE THREAD

**Issue by HarshMakwana27** [danger-ahead/flutter_dictionary#32]
<img src="https://github.com/danger-ahead/flutter_dictionary/assets/133812075/8d36a636-5597-4827-91c1-ae4a64606409" alt="Your Image Description" width="250"> 

OS: Android
Device name: Realme GT NEO2

**Comment by ayato91** [comment]
would you mind if i fix this issue?
that's gonna be my last PR for hacktoberfest :)
