### ISSUE TITLE
Fix loading snackbar while searching for a new word

### ISSUE THREAD

**Issue by danger-ahead** [danger-ahead/flutter_dictionary#4]
Presently the loading snackbar is not properly connected to state. It doesn't wait for the result to arrive before getting dismissed.

Connect the snackbar to state, such that:
- The loading snackbar keeps showing till a result has arrived.
- The snackbar is dismissed as soon as a result has arrived from the API.

**Comment by lejara** [comment]
Hello!

May i take this on?

**Comment by danger-ahead** [comment]
> Hello!
> 
> May i take this on?

Since, it hasn't been solved it. Sure, why not!

Also, you might want to take a look at the project. If you find any potential improvement scopes/bugs, please open an issue. I would put the issue under hacktoberfest as well!

Thanks!
