### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by Rishabh-git10** [danger-ahead/flutter_dictionary#6]
I can update the Readme.md file to better showcase and give more information about the project.
Assign it to me

**Comment by danger-ahead** [comment]
Sure. What do you have in mind regarding this?

**Comment by Rishabh-git10** [comment]
I was thinking I could explain the project a little bit, giving it a nice description, contribution rules, and some screenshots of the app.

**Comment by Rishabh-git10** [comment]
Is it okay If I copy Contribute.md from other repositories from hacktoberfest, as they are essentially the same.

**Comment by danger-ahead** [comment]
> I was thinking I could explain the project a little bit, giving it a nice description, contribution rules, and some screenshots of the app.

Yes that would be very much appreciated. Go ahead!

**Comment by danger-ahead** [comment]
> Is it okay If I copy Contribute.md from other repositories from hacktoberfest, as they are essentially the same ?

As long as you make the necessary changes to align the Contribution guide with our project.

**Comment by Rishabh-git10** [comment]
Okay!
